### ISSUE TITLE
PeriodicTask.stop() does not stop the scheduled task

### ISSUE THREAD

**Issue by mehtaakshay2206** [cGuille/periodic-task#3]
Hi,
     I started a task and I had an condition inside the task function to call the PeriodicTask.stop() to stop it after the condition matches. However I see that the task does not seem to stop.

Please let me know if there is any issue related to this.

Regards,
Akshay

**Comment by cGuille** [comment]
Hello,

I'm surprise someone is using this project. Thanks for your feedback!
I think I understood why this does not work. I am going to fix it.

Regards,
Guillaume.

**Comment by cGuille** [comment]
Can you check if the version `0.1.1` resolve your issue?

**Comment by mehtaakshay2206** [comment]
Thanks Guille for the quick turnaround. Will check and update.

Regards,
Akshay
