### ISSUE TITLE
No way to stop a running task inside the callback

### ISSUE THREAD

**Issue by sayantanhore** [cGuille/periodic-task#6]
Hi,

I am using periodic task in my project. I came across a situation where I needed to stop the task from within the callback. As the API suggests to instantiate a task as below,

`var task = new PeriodicTask(delay, callback, [context], [args])`

I cannot pass the task `task` instance into the `callback` to issue `task.stop()` inside it.

I suggest a workaround here.

`var obj = {};`
`var task = new PeriodicTask(delay, callback, obj, args);`
`obj.stop = task.stop.bind(task);`

If there is any better approach I would appreciate if you inform me. Otherwise would you like to provide a workaround in the API?

Thanks.
Sayantan ...

**Comment by cGuille** [comment]
Hello,

If you declare your `task` variable before defining your task's function, then you can use it inside:

```js
var PeriodicTask = require('periodic-task');

var i = 0;
var task = new PeriodicTask(1000, function () {
        console.log(i++);
        if (i > 3) {
                task.stop();
        }
});
task.run();
```

Thank you for your feedback!

By the way, as stated in the README, have you considered using [async-polling](https://github.com/cGuille/async-polling#readme) instead of this project?
The above sample could be written like this:
```js
var AsyncPolling = require('async-polling');

var i = 0;
function callback(end) {
  console.log(i++);
  if (i > 3) {
    this.stop();
  }
  end();
}

AsyncPolling(callback, 1000).run();
```

**Comment by sayantanhore** [comment]
Hi,

You are right about the first solution, but my situation is a bit more complicated. I have the callbacks declared before and `task` is created and run in another function below. Therefore the `task` is a local variable to that function declared below so somehow I need to pass a `this` reference to the callback to fire `this.stop()`.

No I have not tried `async-polling` but will try and if it works (I am sure it will) will replace `PeriodicTask` with it.

Thanks anyway.

Sayantan ...

**Comment by cGuille** [comment]
I am going to erase the README of this project, advising to go for async-polling instead. I think it is more relevant to use an asynchrone compliant library in JavaScript, so I prefer to improve async-polling and remove periodic-task.

**Comment by sayantanhore** [comment]
Ok, would you consider to mention it as deprecated in the NPM repo? I mean [here](https://www.npmjs.com/package/periodic-task).

**Comment by cGuille** [comment]
That's a good idea. I'll do this. Thank you for your advice!

**Comment by sayantanhore** [comment]
You are welcome.
